task 1:

In [32]:
import numpy as np
a = np.random.random((10, 3))
print(a)
print(a[np.arange(10), np.argmin(abs(a - 0.5), axis = 1)])

[[0.27194674 0.1060676  0.98964407]
 [0.18224846 0.28933983 0.91457815]
 [0.29178152 0.4826057  0.13803794]
 [0.16689137 0.56070481 0.60225025]
 [0.62959974 0.67429983 0.42453568]
 [0.53229748 0.92335761 0.65082693]
 [0.51827846 0.83930011 0.61784528]
 [0.75730499 0.70781381 0.25334849]
 [0.82367043 0.74364032 0.08652207]
 [0.23038264 0.73488718 0.64573552]]
[0.27194674 0.28933983 0.4826057  0.56070481 0.42453568 0.53229748
 0.51827846 0.70781381 0.74364032 0.64573552]


task 2:

In [63]:
a = np.random.random((6, 6))
print(a)
print(np.sum(a, axis = 1) / np.min(a, axis = 0))

[[0.5792758  0.44591024 0.66398507 0.79641664 0.65010745 0.17631709]
 [0.03913435 0.41389882 0.40679013 0.27153601 0.07767989 0.76097622]
 [0.11958344 0.29448419 0.81277653 0.54033489 0.17669917 0.95237442]
 [0.2054244  0.22530683 0.41763484 0.06699408 0.15726846 0.23105413]
 [0.07863356 0.96397677 0.84851784 0.71857473 0.56722633 0.05644444]
 [0.432728   0.28091289 0.32366538 0.99117708 0.65932026 0.72583996]]
[84.63184185  8.74370019  8.94829301 19.45967142 41.62433625 60.47794077]


task 3:

In [149]:
x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0])
print(max(x[np.where(x[np.arange(len(x) - 1)] == 0)[0] + 1]))

5


task 4:

In [164]:
x = np.ones(10)
i = np.array([0, 1, 2, 3, 5, 5, 5, 8])
x += np.bincount(i, minlength = len(x))[np.arange(len(x))]
print(x)

[2. 2. 2. 2. 1. 4. 1. 1. 1. 1.]


task 5 (пока не работает):

In [279]:
def kmeans(obs, k_or_guess, iter = 20, thresh = 1e-05):
    if(type(k_or_guess == int)):
        k = k_or_guess
        (M, N) = obs.shape
        if k >= M:
            res = np.zeros((k, N))
            res[np.arange(M), np.arange(N)] = obs
            return (res, 0)
        i = 0
        p = 1
        thresh_prev = thresh_curr = 0 
        num_of_cluster = np.zeros(M)
        best_dispersion = -1
        diff = thresh + 1
        centroids = np.empty((k, N))
        t = np.arange(k)
        t.shape = ((k, 1))
        while(i < iter):
            if(p == 1):
                start_indices = sorted(np.random.randint(0, M - k + 1, k)) + np.arange(k_or_guess)
                centroids = obs[start_indices]
                centroids.shape = (1, k, N)
                obs.shape = (M, 1, N)
                num_of_cluster = np.argmin(np.sum((obs - centroids) ** 2, axis = 2), axis = 1)
                centroids.shape = (k, N)
                obs.shape = (M, N)
                thresh_prev = np.mean(np.sum((obs - centroids[num_of_cluster]) ** 2, axis = 1))
                p = 0
            centroids.shape = (1, k, N)
            obs.shape = (M, 1, N)
            num_of_cluster = np.argmin(np.sum((obs - centroids) ** 2, axis = 2), axis = 1)
            centroids.shape = (k, N)
            obs.shape = (M, N)
            centroids = np.mean(obs[np.where(num_of_cluster - t == 0)])
            thresh_curr = np.mean(np.sum((obs - centroids[num_of_cluster]) ** 2, axis = 1))
            diff = abs(thresh_curr - thresh_prev)
            if(diff <= thresh):
                diff = thresh + 1
                i += 1
                p = 1
                if(thresh_curr < best_dispersion or best_dispersion == -1):
                    best_dispersion = thresh_curr
                    best_centroids = centroids
        return (best_centroids, best_dispersion)